# campeonato-service - ambiente de producao (container)
server.port=8083
viacep.url=https://viacep.com.br/ws

# Etapa 4: broker de mensagens (RabbitMQ) pelo nome do servico na rede do Compose
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
