# Aplicacao principal - ambiente de desenvolvimento (tudo na mesma maquina)
server.port=8080
campeonato.service.url=http://localhost:8083
spring.cloud.openfeign.client.config.campeonato-service.connectTimeout=2000
spring.cloud.openfeign.client.config.campeonato-service.readTimeout=3000
